/**
 * Instruction Adapter
 *
 * Concatenates memory files (CLAUDE.md) from various sources into a single AGENTS.md file.
 * AGENTS.md is OpenCode's equivalent of CLAUDE.md for project-level instructions.
 *
 * Sources are included in order:
 * - Global (~/.claude/CLAUDE.md)
 * - Project (./CLAUDE.md)
 * - Nested (subdirectory CLAUDE.md files)
 *
 * Also generates skill usage instructions when skills are present.
 */

import type { Rule } from "@ai-systems/shared-types";
import { writeFile } from "fs/promises";
import { join } from "path";

/** Minimal skill info needed for instruction generation */
export interface SkillInfo {
  name: string;
  description: string;
  toolName: string;
}

/**
 * Get a display label for a rule file
 */
function getSourceLabel(rule: Rule): string {
  const sourceType = (rule as { source?: { type?: string } }).source?.type;
  const sourcePath = (rule as { source?: { path?: string } }).source?.path;

  if (sourceType === "global") {
    if (rule.metadata.isMain) {
      return "Global Instructions (from ~/.claude/CLAUDE.md)";
    }
    return `Global Rule (${rule.name})`;
  }
  if (sourceType === "project") {
    if (rule.metadata.isMain) {
      return "Project Instructions (from ./CLAUDE.md)";
    }
    return `Project Rule (${rule.name})`;
  }
  return `Rule (from ${sourcePath || rule.name})`;
}

/**
 * Generate skill usage instructions section
 */
function generateSkillsSection(skills: SkillInfo[]): string {
  if (skills.length === 0) {
    return "";
  }

  const skillsList = skills
    .map((skill) => {
      const desc = skill.description || `Load the ${skill.name} skill`;
      return `- \`${skill.toolName}\`: ${desc}`;
    })
    .join("\n");

  return `## Skills

You have access to skills - specialized capabilities that provide domain knowledge and workflows for specific tasks. Skills are loaded on-demand using skill tools.

### How Skills Work

1. **Invoke a skill tool** when you need its capabilities (e.g., \`skills_pdf\` for PDF work)
2. **The skill expands** into detailed instructions injected into the conversation
3. **Follow the skill's guidance** to complete the task using its specialized knowledge
4. **Use \`read_skill_file\`** to access any supporting files the skill provides

### Available Skills

${skillsList}

### When to Use Skills

- Check skill descriptions to find the right skill for a task
- Invoke a skill BEFORE starting work that matches its domain
- Skills provide specialized tools, patterns, and best practices
- Don't invoke a skill that's already been loaded in the current conversation

### Example Usage

If asked to "create a PDF report", you would:
1. Invoke the appropriate skill tool (e.g., \`skills_pdf\`)
2. Read the expanded skill instructions
3. Follow the skill's guidance for PDF creation
4. Use \`read_skill_file\` if templates or examples are needed`;
}

/**
 * Format the AGENTS.md content from rule files and skills
 */
function formatAgentsMd(rules: Rule[], skills: SkillInfo[] = []): string {
  const parts: string[] = [];

  // Collect sources for header
  const sourcePaths = rules.map((r) => {
    const path = (r as { source?: { path?: string } }).source?.path;
    return path || r.name;
  });
  if (skills.length > 0) {
    sourcePaths.push(`${skills.length} skills`);
  }

  const header = [
    "<!--",
    "  Auto-generated by opencode-claude-adapter",
    `  Sources: ${sourcePaths.join(", ")}`,
    "  Do not edit - changes will be overwritten on next sync",
    "-->",
    "",
  ].join("\n");

  parts.push(header);

  // Add rule sections
  const ruleSections = rules.map((rule) => {
    const sectionHeader = `## ${getSourceLabel(rule)}`;
    const content = rule.content.trim();
    return `${sectionHeader}\n\n${content}`;
  });

  if (ruleSections.length > 0) {
    parts.push(ruleSections.join("\n\n---\n\n"));
  }

  // Add skills section
  const skillsSection = generateSkillsSection(skills);
  if (skillsSection) {
    if (ruleSections.length > 0) {
      parts.push("\n\n---\n\n");
    }
    parts.push(skillsSection);
  }

  return parts.join("") + "\n";
}

/**
 * Sync rule files and skill instructions to AGENTS.md
 *
 * Rules from AgentContext are already flattened and sorted by precedence.
 * Skill instructions are appended when skills are present.
 */
export async function syncInstructions(
  rules: Rule[],
  projectDir: string,
  skills: SkillInfo[] = []
): Promise<{ written: boolean; sources: string[] }> {
  // Only skip if we have nothing to write
  if (rules.length === 0 && skills.length === 0) {
    return { written: false, sources: [] };
  }

  const content = formatAgentsMd(rules, skills);
  const targetPath = join(projectDir, "AGENTS.md");

  await writeFile(targetPath, content, "utf-8");

  const sources = rules.map((r) => {
    const path = (r as { source?: { path?: string } }).source?.path;
    return path || r.name;
  });
  if (skills.length > 0) {
    sources.push(`${skills.length} skills`);
  }

  return {
    written: true,
    sources,
  };
}
