/**
 * Instruction Adapter
 *
 * Concatenates memory files (CLAUDE.md) from various sources into a single AGENTS.md file.
 * AGENTS.md is OpenCode's equivalent of CLAUDE.md for project-level instructions.
 *
 * Sources are included in order:
 * - Global (~/.claude/CLAUDE.md)
 * - Project (./CLAUDE.md)
 * - Nested (subdirectory CLAUDE.md files)
 */

import type { MemoryFile } from "@ai-systems/shared-types";
import { writeFile } from "fs/promises";
import { join } from "path";

/**
 * Get a display label for a memory file
 */
function getSourceLabel(file: MemoryFile): string {
  if (file.scope === "global") {
    return "Global Instructions (from ~/.claude/CLAUDE.md)";
  }
  if (file.scope === "project") {
    return "Project Instructions (from ./CLAUDE.md)";
  }
  // nested or unknown
  return `Directory Instructions (from ${file.relativePath || file.path})`;
}

/**
 * Format the AGENTS.md content from memory files
 */
function formatAgentsMd(files: MemoryFile[]): string {
  if (files.length === 0) {
    return "";
  }

  const sourcePaths = files.map((f) => f.relativePath || f.path).join(", ");

  const header = [
    "<!--",
    "  Auto-generated by opencode-claude-adapter",
    `  Sources: ${sourcePaths}`,
    "  Do not edit - changes will be overwritten on next sync",
    "-->",
    "",
  ].join("\n");

  const sections = files.map((file) => {
    const sectionHeader = `## ${getSourceLabel(file)}`;
    const content = file.content.trim();
    return `${sectionHeader}\n\n${content}`;
  });

  return header + sections.join("\n\n---\n\n") + "\n";
}

/**
 * Sync memory files (CLAUDE.md) to AGENTS.md
 *
 * Memory files from AgentContext are already flattened and sorted by precedence.
 */
export async function syncInstructions(
  memoryFiles: MemoryFile[],
  projectDir: string
): Promise<{ written: boolean; sources: string[] }> {
  if (memoryFiles.length === 0) {
    return { written: false, sources: [] };
  }

  const content = formatAgentsMd(memoryFiles);
  const targetPath = join(projectDir, "AGENTS.md");

  await writeFile(targetPath, content, "utf-8");

  return {
    written: true,
    sources: memoryFiles.map((f) => f.relativePath || f.path),
  };
}
