/**
 * Instruction Transformer
 *
 * Transforms CLAUDE.md memory files into AGENTS.md format for OpenCode.
 * Also generates skill usage instructions when skills are present.
 */

import type { MemoryFile } from "@ai-systems/shared-types";

/**
 * Minimal skill info needed for instruction generation
 */
export interface SkillInfo {
  name: string;
  description: string;
  toolName: string;
}

/**
 * Get a display label for a memory file
 */
function getSourceLabel(file: MemoryFile): string {
  if (file.scope === "global") {
    return "Global Instructions (from ~/.claude/CLAUDE.md)";
  }
  if (file.scope === "project") {
    return "Project Instructions (from ./CLAUDE.md)";
  }
  // nested or unknown
  return `Directory Instructions (from ${file.relativePath || file.path})`;
}

/**
 * Generate skill usage instructions section
 */
export function generateSkillsSection(skills: SkillInfo[]): string {
  if (skills.length === 0) {
    return "";
  }

  const skillsList = skills
    .map((skill) => {
      const desc = skill.description || `Load the ${skill.name} skill`;
      return `- \`${skill.toolName}\`: ${desc}`;
    })
    .join("\n");

  return `## Skills

You have access to skills - specialized capabilities that provide domain knowledge and workflows for specific tasks. Skills are loaded on-demand using skill tools.

### How Skills Work

1. **Invoke a skill tool** when you need its capabilities (e.g., \`skills_pdf\` for PDF work)
2. **The skill expands** into detailed instructions injected into the conversation
3. **Follow the skill's guidance** to complete the task using its specialized knowledge
4. **Use \`read_skill_file\`** to access any supporting files the skill provides

### Available Skills

${skillsList}

### When to Use Skills

- Check skill descriptions to find the right skill for a task
- Invoke a skill BEFORE starting work that matches its domain
- Skills provide specialized tools, patterns, and best practices
- Don't invoke a skill that's already been loaded in the current conversation

### Example Usage

If asked to "create a PDF report", you would:
1. Invoke the appropriate skill tool (e.g., \`skills_pdf\`)
2. Read the expanded skill instructions
3. Follow the skill's guidance for PDF creation
4. Use \`read_skill_file\` if templates or examples are needed`;
}

/**
 * Format the AGENTS.md content from memory files and skills
 *
 * @param files - Memory files (CLAUDE.md) from various sources
 * @param skills - Optional skill information for instruction generation
 * @returns Formatted AGENTS.md content
 */
export function formatAgentsMd(
  files: MemoryFile[],
  skills: SkillInfo[] = []
): string {
  const parts: string[] = [];

  // Collect sources for header
  const sourcePaths = files.map((f) => f.relativePath || f.path);
  if (skills.length > 0) {
    sourcePaths.push(`${skills.length} skills`);
  }

  const header = [
    "<!--",
    "  Auto-generated by opencode-claude-adapter",
    `  Sources: ${sourcePaths.join(", ")}`,
    "  Do not edit - changes will be overwritten on next sync",
    "-->",
    "",
  ].join("\n");

  parts.push(header);

  // Add memory file sections
  const memoryFileSections = files.map((file) => {
    const sectionHeader = `## ${getSourceLabel(file)}`;
    const content = file.content.trim();
    return `${sectionHeader}\n\n${content}`;
  });

  if (memoryFileSections.length > 0) {
    parts.push(memoryFileSections.join("\n\n---\n\n"));
  }

  // Add skills section
  const skillsSection = generateSkillsSection(skills);
  if (skillsSection) {
    if (memoryFileSections.length > 0) {
      parts.push("\n\n---\n\n");
    }
    parts.push(skillsSection);
  }

  return parts.join("") + "\n";
}
