/**
 * Instruction Adapter
 *
 * Concatenates CLAUDE.md files from various sources into a single AGENTS.md file.
 * AGENTS.md is OpenCode's equivalent of CLAUDE.md for project-level instructions.
 *
 * Sources are included in order:
 * - Global (~/.claude/CLAUDE.md)
 * - Project (./CLAUDE.md)
 * - Nested (subdirectory CLAUDE.md files)
 */

import type { ClaudeMdNode, ClaudeMdFile } from "@hhopkins/claude-entity-manager";
import { writeFile } from "fs/promises";
import { join } from "path";

/**
 * Flatten the ClaudeMdNode tree into a list of files
 */
function flattenClaudeMdNodes(nodes: ClaudeMdNode[]): ClaudeMdFile[] {
  const files: ClaudeMdFile[] = [];

  function traverse(node: ClaudeMdNode) {
    if (node.type === "file" && node.file) {
      files.push(node.file);
    }
    if (node.children) {
      for (const child of node.children) {
        traverse(child);
      }
    }
  }

  for (const node of nodes) {
    traverse(node);
  }

  // Sort by scope priority: global first, then project, then nested
  const scopeOrder = { global: 0, project: 1, nested: 2 };
  files.sort((a, b) => {
    const orderDiff = scopeOrder[a.scope] - scopeOrder[b.scope];
    if (orderDiff !== 0) return orderDiff;
    // For nested files, sort by level then path
    if (a.scope === "nested" && b.scope === "nested") {
      if (a.level !== b.level) return a.level - b.level;
      return a.path.localeCompare(b.path);
    }
    return 0;
  });

  return files;
}

/**
 * Get a display label for a CLAUDE.md file
 */
function getSourceLabel(file: ClaudeMdFile): string {
  switch (file.scope) {
    case "global":
      return "Global Instructions (from ~/.claude/CLAUDE.md)";
    case "project":
      return "Project Instructions (from ./CLAUDE.md)";
    case "nested":
      return `Directory Instructions (from ${file.relativePath})`;
  }
}

/**
 * Format the AGENTS.md content from CLAUDE.md files
 */
function formatAgentsMd(files: ClaudeMdFile[]): string {
  if (files.length === 0) {
    return "";
  }

  const sourcePaths = files.map((f) => f.relativePath || f.path).join(", ");

  const header = [
    "<!--",
    "  Auto-generated by opencode-claude-adapter",
    `  Sources: ${sourcePaths}`,
    "  Do not edit - changes will be overwritten on next sync",
    "-->",
    "",
  ].join("\n");

  const sections = files.map((file) => {
    const sectionHeader = `## ${getSourceLabel(file)}`;
    const content = file.content.trim();
    return `${sectionHeader}\n\n${content}`;
  });

  return header + sections.join("\n\n---\n\n") + "\n";
}

/**
 * Sync CLAUDE.md files to AGENTS.md
 */
export async function syncInstructions(
  claudeMdNodes: ClaudeMdNode[],
  projectDir: string
): Promise<{ written: boolean; sources: string[] }> {
  const files = flattenClaudeMdNodes(claudeMdNodes);

  if (files.length === 0) {
    return { written: false, sources: [] };
  }

  const content = formatAgentsMd(files);
  const targetPath = join(projectDir, "AGENTS.md");

  await writeFile(targetPath, content, "utf-8");

  return {
    written: true,
    sources: files.map((f) => f.relativePath || f.path),
  };
}
